name: macOS

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-15
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      with: 
        swift-version: '6.1.0'
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
      env:
        APPSTATE_STRICT: "1"
    - name: Run tests
      run: swift test -v
      env:
        APPSTATE_STRICT: "1"
    - name: Build SwiftData example
      run: swift build -v
      working-directory: Examples/SwiftDataExample
    - name: Run SwiftData example
      run: swift run
      working-directory: Examples/SwiftDataExample
